# Generated by Django 4.1.6 on 2023-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='news', through='main.PostCategory', to='main.category'),
        ),
    ]
