# Generated by Django 4.1.6 on 2023-06-19 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(choices=[('ST', 'Спорт'), ('ED', 'Образование'), ('MS', 'Музыка'), ('NT', 'Природа')], default='ED', help_text='category name', max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(choices=[('ST', 'Спорт'), ('ED', 'Образование'), ('MS', 'Музыка'), ('NT', 'Природа')], default='ED', help_text='category name', max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('ST', 'Спорт'), ('ED', 'Образование'), ('MS', 'Музыка'), ('NT', 'Природа')], default='ED', help_text='category name', max_length=2, unique=True),
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='main.category', verbose_name='This is the help text')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='main.CategorySubscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
